apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "handover-ifx.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "handover-ifx.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "handover-ifx.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "handover-ifx.name" . }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "handover-ifx.fullname" . }}
      imagePullSecrets:
        - name: {{ .Values.serviceAccount.imagePullSecrets }}
      containers:
        - name: handover-ifx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
