apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "handover-ifx.fullname" . }}
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
